### ISSUE TITLE
raw data

### ISSUE THREAD

**Issue by hieonn** [lsjsj92/machine_learning_basic#1]
좋은 노트북 공유 감사합니다. 

raw data는 공유할 계획이 없으신지요? 

감사합니다.

**Comment by lsjsj92** [comment]
안녕하세요~
데이터는 현재 제가 소유하고 있지 않습니다 ㅠ
대부분 kaggle이나 구글에서 나온 데이터로 사용했습니다 ~ 관련 데이터는 아마 구글에 찾으시면 많이 나올거에요!

**Comment by hieonn** [comment]
감사합니다!
